double customPow(double basis, int exponent);
long long customFac(int x);
double customAbs(double x);
long long sign(int n);
double customLn(double x);
double customSqrt(double x);
double customFloor(double x);
long long customDoubleFac(int n);
long roundToLong(double x);
double customExp(double x);
double customLn_V1(double x);
long long halfFac(int n);
double customPow2(int n);
